create table if not exists public.srs_cards (
  id bigint generated by default as identity primary key,
  study_set_id integer not null,
  hanzi text not null,
  due timestamptz not null default now(),
  stability real not null default 0,
  difficulty real not null default 0,
  elapsed_days integer not null default 0,
  scheduled_days integer not null default 0,
  reps integer not null default 0,
  lapses integer not null default 0,
  state smallint not null default 0,
  last_review timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint unique_study_set_hanzi unique (study_set_id, hanzi)
);

alter table public.srs_cards enable row level security;

create policy "allow_all_anon" on public.srs_cards
  for all
  to anon
  using (true)
  with check (true);
