create table if not exists public.vocabulary_entries (
  id bigint primary key generated by default as identity,
  hanzi text not null,
  pinyin text not null default '',
  meanings jsonb not null default '[]'::jsonb,
  compounds jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.vocabulary_entries enable row level security;

create policy "allow_all_anon" on public.vocabulary_entries
  for all
  to anon
  using (true)
  with check (true);
