-- Enable pg_trgm for fuzzy text search
create extension if not exists pg_trgm;

-- 1. Learning paths
create table if not exists public.paths (
  id int primary key,
  title text not null,
  tags text not null
);

-- 2. Study sets
create table if not exists public.study_sets (
  id int primary key,
  path_id int not null references public.paths(id) on delete cascade,
  title text not null,
  word_count int not null default 0
);

-- 3. Vocabulary
create table if not exists public.vocabulary (
  id bigint primary key generated by default as identity,
  set_id int not null references public.study_sets(id) on delete cascade,
  hanzi text not null,
  pinyin text not null,
  vietnamese text not null,
  type text not null default '',
  example text not null default '',
  synonyms jsonb not null default '[]'::jsonb,
  unique(set_id, hanzi)
);

create index if not exists idx_vocabulary_set_id on public.vocabulary(set_id);
create index if not exists idx_vocabulary_hanzi on public.vocabulary using gin(hanzi gin_trgm_ops);
create index if not exists idx_vocabulary_pinyin on public.vocabulary using gin(pinyin gin_trgm_ops);
create index if not exists idx_vocabulary_vietnamese on public.vocabulary using gin(vietnamese gin_trgm_ops);

-- 4. Phonetic table
create table if not exists public.phonetic (
  id bigint primary key generated by default as identity,
  row_idx int not null,
  col_idx int not null,
  text jsonb not null default '[]'::jsonb,
  type int not null default 0,
  audio jsonb not null default '[]'::jsonb,
  join_text text not null default '',
  original_id text not null default '',
  filename text not null default '',
  is_null bool not null default false
);

create index if not exists idx_phonetic_position on public.phonetic(row_idx, col_idx);

-- 5. Update srs_cards with FK to vocabulary
alter table public.srs_cards
  add column if not exists vocabulary_id bigint references public.vocabulary(id) on delete cascade;

-- RLS for all tables
alter table public.paths enable row level security;
alter table public.study_sets enable row level security;
alter table public.vocabulary enable row level security;
alter table public.phonetic enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'paths' and policyname = 'allow_all_anon') then
    create policy "allow_all_anon" on public.paths for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'study_sets' and policyname = 'allow_all_anon') then
    create policy "allow_all_anon" on public.study_sets for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'vocabulary' and policyname = 'allow_all_anon') then
    create policy "allow_all_anon" on public.vocabulary for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'phonetic' and policyname = 'allow_all_anon') then
    create policy "allow_all_anon" on public.phonetic for all to anon using (true) with check (true);
  end if;
end $$;
